name: Associate Cloud Engineer PDF Generator

on:
  workflow_dispatch:

jobs:
  generate_pdfs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install necessary packages and binaries (including wkhtmltopdf)
      - name: Install wkhtmltopdf and jot
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf
          sudo apt-get install -y jot

      # Step 3: Ensure that the input file exists
      - name: Ensure input file exists
        run: |
          if [ ! -f "./associate-cloud-engineer.txt" ]; then
            echo "Input file not found! Exiting."
            exit 1
          fi

      # Step 4: Execute the loop from the file, generating PDFs
      - name: Execute wkhtmltopdf commands with delay
        run: |
          while read line; do
            bash -c "($line 2>&1 | tee -a ./report)"
            sleep $(jot -r 1 3 8)
          done < ./associate-cloud-engineer.txt
