name: Associate Cloud Engineer PDF Generator

on:
  workflow_dispatch:

jobs:
  generate_pdfs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install necessary packages and binaries (including wkhtmltopdf)
      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq wkhtmltopdf

      # Step 3: Ensure that the input file exists
      - name: Ensure input file exists
        run: |
          if [ ! -f "./associate-cloud-engineer.txt" ]; then
            echo "Input file not found! Exiting."
            exit 1
          fi

      # Step 4: Execute the loop from the file, generating PDFs
      # Step 4: Execute wkhtmltopdf commands with delay and error reporting
      - name: Execute wkhtmltopdf commands with delay and error handling
        run: |
          while read line; do
            # Enhanced wkhtmltopdf command with error handling
            if ! bash -c "($line --no-stop-slow-scripts --disable-smart-shrinking 2>&1 | tee -a ./report)"; then
              echo "Error occurred during: $line" >> ./report
            fi
            sleep $(shuf -i 3-8 -n 1)
          done < ./associate-cloud-engineer.txt

      # Step 6: Commit and push the report and any generated files
      - name: Commit and push changes
        run: |
          git add report *.pdf
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Add generated PDFs and report from GitHub Action"
            git push origin main
          fi
